remote_theme: pmarsceill/just-the-docs
title: Theme pack support
description: Theme pack support for Sailfish OS
baseurl: ""
exclude: ["appicons/", "images/", "qml/", "rpm/", "scripts/", "src/", "translations/", "LICENSE", "*.desktop", "*.pro"]

url: "https://fravaccaro.github.io/sailfishos-uithemer"
search_enabled: true
aux_links:
    "UI Themer on GitHub":
      - "//github.com/fravaccaro/sailfishos-uithemer"
